// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BaseModel struct {
	ID        *string `json:"id,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	DeletedAt *string `json:"deleted_at,omitempty"`
}

type BaseModelInput struct {
	ID        *string `json:"id,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	DeletedAt *string `json:"deleted_at,omitempty"`
}

type Campaign struct {
	ID        *string  `json:"id,omitempty"`
	Name      *string  `json:"name,omitempty"`
	BeginDate *string  `json:"begin_date,omitempty"`
	Events    []*Event `json:"events,omitempty"`
	UserID    *string  `json:"user_id,omitempty"`
}

type CampaignInput struct {
	ID        *string `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
	BeginDate *string `json:"begin_date,omitempty"`
	UserID    *string `json:"user_id,omitempty"`
}

type Event struct {
	ID          *string   `json:"id,omitempty"`
	Title       *string   `json:"title,omitempty"`
	Description *string   `json:"description,omitempty"`
	StartTime   *string   `json:"startTime,omitempty"`
	LocationID  *string   `json:"location_id,omitempty"`
	CampaignID  *string   `json:"campaign_id,omitempty"`
	ProjectID   *string   `json:"project_id,omitempty"`
	TaskID      *string   `json:"task_id,omitempty"`
	Tasks       []*Task   `json:"tasks,omitempty"`
	Location    *Location `json:"location,omitempty"`
}

type EventInput struct {
	ID          *string `json:"id,omitempty"`
	Title       *string `json:"Title,omitempty"`
	Description *string `json:"Description,omitempty"`
	StartTime   *string `json:"startTime,omitempty"`
	LocationID  *string `json:"LocationID,omitempty"`
	CampaignID  *string `json:"CampaignID,omitempty"`
	ProjectID   *string `json:"ProjectID,omitempty"`
	TaskID      *string `json:"TaskID,omitempty"`
}

type Location struct {
	ID          *string `json:"id,omitempty"`
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	StartTime   *string `json:"start_time,omitempty"`
	EndTime     *string `json:"end_time,omitempty"`
	Street      *string `json:"street,omitempty"`
}

type LocationInput struct {
	ID          *string `json:"id,omitempty"`
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	StartTime   *string `json:"start_time,omitempty"`
	EndTime     *string `json:"end_time,omitempty"`
	Street      *string `json:"street,omitempty"`
}

type Project struct {
	ID        *string  `json:"id,omitempty"`
	Name      *string  `json:"name,omitempty"`
	BeginDate *string  `json:"begin_date,omitempty"`
	Events    []*Event `json:"events,omitempty"`
	UserID    *string  `json:"user_id,omitempty"`
}

type ProjectInput struct {
	ID        *string `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
	BeginDate *string `json:"begin_date,omitempty"`
	UserID    *string `json:"user_id,omitempty"`
}

type Task struct {
	ID             *string           `json:"id,omitempty"`
	Name           *string           `json:"name,omitempty"`
	Date           *string           `json:"date,omitempty"`
	Taken          *bool             `json:"taken,omitempty"`
	EventID        *string           `json:"event_id,omitempty"`
	UserID         *string           `json:"user_id,omitempty"`
	TaskAssignment []*TaskAssignment `json:"task_assignment,omitempty"`
}

type TaskAssignment struct {
	ID     *string `json:"id,omitempty"`
	TaskID *string `json:"task_id,omitempty"`
	UserID *string `json:"user_id,omitempty"`
	User   *User   `json:"user,omitempty"`
	Task   *Task   `json:"task,omitempty"`
}

type TaskAssignmentInput struct {
	ID     *string `json:"id,omitempty"`
	TaskID *string `json:"task_id,omitempty"`
	UserID *string `json:"user_id,omitempty"`
}

type TaskInput struct {
	ID      *string `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
	Date    *string `json:"date,omitempty"`
	Taken   *bool   `json:"taken,omitempty"`
	EventID *string `json:"event_id,omitempty"`
}

type User struct {
	ID        *string     `json:"id,omitempty"`
	FirstName *string     `json:"firstName,omitempty"`
	LastName  *string     `json:"lastName,omitempty"`
	Email     *string     `json:"Email,omitempty"`
	Phone     *string     `json:"phone,omitempty"`
	Campaigns []*Campaign `json:"campaigns,omitempty"`
	Projects  []*Project  `json:"projects,omitempty"`
}

type UserInput struct {
	ID        *string `json:"id,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Email     *string `json:"Email,omitempty"`
	Phone     *string `json:"phone,omitempty"`
}
